### ISSUE TITLE
Error when pulling gl_accounts

### ISSUE THREAD

**Issue by nazmiasri95** [singer-io/tap-mambu#51]
Getting error from tap-mambu when pulling data for gl-accounts:
```
Traceback (most recent call last):
  File "/usr/local/bin/tap-mambu", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/singer/utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tap_mambu/__init__.py", line 52, in main
    state=state)
  File "/usr/local/lib/python3.7/site-packages/tap_mambu/sync.py", line 834, in sync
    id_fields=endpoint_config.get('id_fields'))
  File "/usr/local/lib/python3.7/site-packages/tap_mambu/sync.py", line 148, in sync_endpoint
    last_datetime = get_bookmark(state, stream_name, sub_type, start_date)
  File "/usr/local/lib/python3.7/site-packages/tap_mambu/sync.py", line 38, in get_bookmark
    return (state.get('bookmarks', {}).get(stream, {}).get(sub_type, default))
AttributeError: 'str' object has no attribute 'get'
```

Here is the command it's running. Inside the config.json, only gl-accounts were enabled (selected=true). State just mentioning to pull data since 2 days ago
`tap-mambu --config config.json --catalog catalog.json --state state.json`

Kindly check on this

**Comment by nazmiasri95** [comment]
Found out it was issue with my `catalog.json`. Copied the original one and update from there. The `state.json` also need to be updated in correct format, can get the sample once run without `state.json`.
