### ISSUE TITLE
ImportError: cannot import name 'strptime_to_utc' from 'singer.utils' (/opt/homebrew/lib/python3.9/site-packages/singer/utils.py)

### ISSUE THREAD

**Issue by rajeshanbarasu** [singer-io/tap-mambu#94]
Hi All

I am setting up the tap-mambu (as per the documentation) on my local machine and get the below error when I try to run the tap. Please let me know if I am missing anything

_I am not an expert in python. So, please let me know if I am missing any basic stuff._ 

`Traceback (most recent call last):
  File "/opt/homebrew/bin/tap-mambu", line 5, in <module>
    from tap_mambu import main
  File "/opt/homebrew/lib/python3.9/site-packages/tap_mambu/__init__.py", line 8, in <module>
    from tap_mambu.sync import sync_all_streams
  File "/opt/homebrew/lib/python3.9/site-packages/tap_mambu/sync.py", line 4, in <module>
    from .helpers.generator_processor_pairs import get_generator_processor_for_stream, get_stream_subtypes
  File "/opt/homebrew/lib/python3.9/site-packages/tap_mambu/helpers/generator_processor_pairs.py", line 25, in <module>
    from ..tap_processors.audit_trail_processor import AuditTrailProcessor
  File "/opt/homebrew/lib/python3.9/site-packages/tap_mambu/tap_processors/audit_trail_processor.py", line 1, in <module>
    from .processor import TapProcessor
  File "/opt/homebrew/lib/python3.9/site-packages/tap_mambu/tap_processors/processor.py", line 4, in <module>
    from singer.utils import strptime_to_utc, now as singer_now
ImportError: cannot import name 'strptime_to_utc' from 'singer.utils' (/opt/homebrew/lib/python3.9/site-packages/singer/utils.py)`

**Comment by svlada** [comment]
@rajeshanbarasu Have found solution? I'm having the same issue.

**Comment by aducci** [comment]
found that you can avoid this error by installing inside a vEnv and installing dependencies using "pip install ." 
`
brew install virtualenv
Python3 -m venv ~/.virtualenvs/tap-mambu
source ~/.virtualenvs/tap-mambu/bin/activate
Git clone https://github.com/singer-io/tap-mambu.git
Pip install .
`
